/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_4ACCBAA__
#define __PLUGINEDITOR_H_4ACCBAA__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "PartialLevelsComponent.h"
#include "ADSREditor.h"
#include "kernel.h"


//==============================================================================
/** This is the editor component that our filter will display.
*/
class PluginEditor  : public AudioProcessorEditor
{
public:
    PluginEditor (PluginProcessor&);
    ~PluginEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

	// Called by other UI components (or self) when the parameters have been manually changed
	void parametersChanged();

private:
	ParameterStates parameterStates;
    MidiKeyboardComponent midiKeyboard;
	PartialLevelsComponent partialLevelsComponent;
	ADSREditor volumeADSR, volumeLFOFreq, volumeLFODepth;
    ScopedPointer<ResizableCornerComponent> resizer;
    ComponentBoundsConstrainer resizeLimits;

    PluginProcessor& getProcessor() const
    {
		return static_cast<PluginProcessor&> (processor);
    }
};


#endif  // __PLUGINEDITOR_H_4ACCBAA__
